<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wheelchair">  

  <xacro:include filename="$(find baxter_wheelchair_description)/urdf/sensors/kinect_camera.urdf.xacro" />

  <xacro:property name="PI" value="3.14159265359" />
  <xacro:property name="M_PI" value="3.1415926535897931" />

  <xacro:property name="chair_width" value="0.643" /> <!-- From front wheel right joint to front wheel left joint -->
  <xacro:property name="chair_length" value="0.812" /> <!-- From front wheel joint to back wheel joint -->
  <!-- <xacro:property name="chair_height" value="1.191" /> --> <!-- From front wheel joint to head rest -->
  <xacro:property name="chair_height" value="0.4" /> <!-- From front wheel joint to approx height -->
  <xacro:property name="chair_weight" value="10.0" />
  
  <xacro:property name="main_wheel_length" value="0.065" />
  <xacro:property name="main_wheel_radius" value=".165" />
  <xacro:property name="main_wheel_weight" value="2.0" />

  <xacro:property name="small_wheel_radius" value=".089" />
  <xacro:property name="small_wheel_length" value=".05" />
  <xacro:property name="small_wheel_weight" value="1.0" />

  <!-- Kinect Camera Location (Nominally 0) -->
  <xacro:property name="cal_kinect_x" value="0.0" />
  <xacro:property name="cal_kinect_y" value="0.0" />
  <xacro:property name="cal_kinect_z" value="0.0" />
  <xacro:property name="cal_kinect_roll" value="0.0" />
  <xacro:property name="cal_kinect_pitch" value="0.0" />
  <xacro:property name="cal_kinect_yaw" value="0.0" />

  <xacro:macro name="box_intertia" params="height length width weight" >
    <inertia ixx="${1/12 * weight * (height + length)}" ixy="0" ixz="0" iyy="${1/12 * weight * (width + length)}" iyz="0" izz="${1/12 * weight * (width + height)}" />
  </xacro:macro>

  <xacro:macro name="cylinder_intertia" params="length radius weight" >
    <inertia ixx="${1/12 * weight * (3 * radius * radius + length * length)}" ixy="0" ixz="0" iyy="${1/12 * weight * (3 * radius*radius + length*length)}" iyz="0" izz="${1/2 * weight * radius*radius}" />
  </xacro:macro>

  <link name="base_footprint">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.001 0.001 0.001" />
      </geometry>
    </visual>
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <!-- <origin xyz=" 0 0 0.7" rpy="0 0 0"/> -->
    <origin xyz=" 0 0 0.3" rpy="0 0 0"/> <!-- accomodating for change in chair height -->
    <parent link="base_footprint"/>
    <child link="base_link"/>
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chair_length} ${chair_width} ${chair_height}"/>
      </geometry>
      <material name="darkgray">
        <color rgba=".2 .2 .2 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${chair_length} ${chair_width} ${chair_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${chair_weight}"/>
      <xacro:box_intertia height="${chair_height}" length="${chair_length}" width="${chair_width}" weight="${chair_weight}" />
    </inertial>
  </link>

  <!-- Base of Kinect Mount -->
  <xacro:kinect_camera_v0 name="kinect_camera" parent="base_link" >
    <origin xyz="${chair_length/2 - 0.02} 0 ${chair_height/2 + 0.05}" rpy="0 0 0" />
  </xacro:kinect_camera_v0>

  <link name="imu_link">
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1.0E-6" ixy="0" ixz="0" iyy="1.0E-6" iyz="0" izz="1.0E-6"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
    </visual>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="${PI} 0 0"/>
  </joint>

<!--Right Bar -->
  <link name="right_bar">
    <visual>
      <geometry>
        <box size="${chair_length + chair_length/4} ${chair_width/4} ${chair_height/8}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 0.8"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${chair_length + chair_length/4} ${chair_width/4} ${chair_height/8}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <inertia ixx="1e-3" ixy="1e-3" ixz="1e-3" iyy="1e-3" iyz="1e-3" izz="1e-3"/>
    </inertial>
  </link>

  <joint name="right_bar_joint" type="fixed">
    <axis xyz="0 0 0"/>
    <parent link="base_link"/>
    <child link="right_bar"/>
    <origin rpy="0 0 0" xyz="0.0 ${chair_width/2} -${chair_height/4 + chair_height/8}"/> <!--chair_height/4 + chair_height/8 because this is relative to the center of the bar -->
  </joint>

<!--Left Bar -->
  <link name="left_bar">
    <visual>
      <geometry>
        <box size="${chair_length + chair_length/4} ${chair_width/4} ${chair_height/8}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 0.8"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${chair_length + chair_length/4} ${chair_width/4} ${chair_height/8}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <inertia ixx="1e-3" ixy="1e-3" ixz="1e-3" iyy="1e-3" iyz="1e-3" izz="1e-3"/>
    </inertial>
  </link>

  <joint name="left_bar_joint" type="fixed">
    <axis xyz="0 0 0"/>
    <parent link="base_link"/>
    <child link="left_bar"/>
    <origin rpy="0 0 0" xyz="0.0 -${chair_width/2} -${chair_height/4 + chair_height/8}"/> <!--chair_height/4 + chair_height/8 because this is relative to the center of the bar -->
  </joint>

<!--Main Wheels -->
  <joint name="right_main_wheel_joint" type="continuous">
    <axis xyz="0 0 -1"/>
    <parent link="right_bar"/>
    <child link="right_main_wheel"/>
    <!-- <origin rpy="1.57075 0 0" xyz="0.0 0.0 -${chair_height/8-0.076}"/> -->
    <origin rpy="1.57075 0 0" xyz="0.0 0.0 ${main_wheel_radius - chair_height/8 - small_wheel_radius}"/> <!-- accomodating for change in chair height -->
  </joint>

  <link name="right_main_wheel">
    <visual>
      <geometry>
        <cylinder length="${main_wheel_length}" radius="${main_wheel_radius}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${main_wheel_length}" radius="${main_wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${main_wheel_weight}"/>
      <xacro:cylinder_intertia length="${main_wheel_length}" radius="${main_wheel_radius}" weight="${main_wheel_weight}" />
    </inertial>
  </link>

  <joint name="left_main_wheel_joint" type="continuous">
    <axis xyz="0 0 -1"/>
    <parent link="left_bar"/>
    <child link="left_main_wheel"/>
    <!-- <origin rpy="1.57075 0 0" xyz="0.0 0.0 -${chair_height/8-0.076}"/> -->
    <origin rpy="1.57075 0 0" xyz="0.0 0.0 ${main_wheel_radius - chair_height/8 - small_wheel_radius}"/> <!-- accomodating for change in chair height -->
  </joint>

  <link name="left_main_wheel">
    <visual>
      <geometry>
        <cylinder length="${main_wheel_length}" radius="${main_wheel_radius}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${main_wheel_length}" radius="${main_wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${main_wheel_weight}"/>
      <xacro:cylinder_intertia length="${main_wheel_length}" radius="${main_wheel_radius}" weight="${main_wheel_weight}" />
    </inertial>
  </link>

<!--Front Wheels -->
  <link name="front_right_swivel">
    <visual>
      <geometry>
        <cylinder length="0.065" radius="0.01"/>
      </geometry>
      <material name="darkgray">
        <color rgba=".2 .2 .2 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.065" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value=".1"/>
      <xacro:cylinder_intertia length="0.065" radius="0.01" weight="0.1" />
    </inertial>
  </link>

  <joint name="front_right_swivel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="right_bar"/>
    <child link="front_right_swivel"/>
    <origin rpy="0 0 0" xyz="-${chair_length/2} 0.0 -${chair_height/8}"/>
    <dynamics damping="0.0" friction="0.5" />
  </joint>

  <joint name="front_right_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="front_right_swivel"/>
    <child link="front_right_wheel"/>
    <origin rpy="1.57075 0 0" xyz="0.065 0 0"/>
    <dynamics damping="0.0" friction="0.5" />
  </joint>

  <link name="front_right_wheel">
    <visual>
      <geometry>
        <cylinder length="${small_wheel_length}" radius="${small_wheel_radius}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${small_wheel_length}" radius="${small_wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <mass value="${small_wheel_weight}"/>
      <xacro:cylinder_intertia length="${small_wheel_length}" radius="${small_wheel_radius}" weight="${small_wheel_weight}" />
    </inertial>
  </link>
  <link name="front_left_swivel">
    <visual>
      <geometry>
        <cylinder length="0.065" radius="0.01"/>
      </geometry>
      <material name="darkgray">
        <color rgba=".2 .2 .2 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.065" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value=".1"/>
      <xacro:cylinder_intertia length="0.065" radius="0.01" weight="0.1" />
    </inertial>
  </link>

  <joint name="front_left_swivel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="left_bar"/>
    <child link="front_left_swivel"/>
    <origin rpy="0 0 0" xyz="-${chair_length/2} 0.0 -${chair_height/8}"/>
    <dynamics damping="0.0" friction="0.5" />
  </joint>

  <joint name="front_left_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="front_left_swivel"/>
    <child link="front_left_wheel"/>
    <origin rpy="1.57075 0 0" xyz="0.065 0 0"/>
    <dynamics damping="0" friction="0.5" />
  </joint>

  <link name="front_left_wheel">
    <visual>
      <geometry>
        <cylinder length="0.05" radius="${small_wheel_radius}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="${small_wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <mass value="${small_wheel_weight}"/>
      <xacro:cylinder_intertia length="${small_wheel_length}" radius="${small_wheel_radius}" weight="${small_wheel_weight}" />
    </inertial>
  </link>

<!--Rear Wheels -->
  <link name="rear_right_swivel">
    <visual>
      <geometry>
        <cylinder length="0.065" radius="0.01"/>
      </geometry>
      <material name="darkgray">
        <color rgba=".2 .2 .2 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.065" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value=".1"/>
      <xacro:cylinder_intertia length="0.065" radius="0.01" weight="0.1" />
    </inertial>
  </link>

   <joint name="rear_right_swivel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="right_bar"/>
    <child link="rear_right_swivel"/>
    <origin rpy="0 0 0" xyz="${chair_length/2} 0.0 -${chair_height/8}"/>
    <dynamics damping="0.0" friction="0.5" />
  </joint>

  <joint name="rear_right_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="rear_right_swivel"/>
    <child link="rear_right_wheel"/>
    <origin rpy="1.57075 0 0" xyz="0.065 0 0"/>
    <dynamics damping="0" friction="0.5" />
  </joint>

  <link name="rear_right_wheel">
    <visual>
      <geometry>
        <cylinder length="0.05" radius="${small_wheel_radius}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="${small_wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <mass value="${small_wheel_weight}"/>
      <xacro:cylinder_intertia length="${small_wheel_length}" radius="${small_wheel_radius}" weight="${small_wheel_weight}" />
    </inertial>
  </link>

  <link name="rear_left_swivel">
    <visual>
      <geometry>
        <cylinder length="0.065" radius="0.01"/>
      </geometry>
      <material name="darkgray">
        <color rgba=".2 .2 .2 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.065" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value=".1"/>
      <xacro:cylinder_intertia length="0.065" radius="0.01" weight="0.1" />
    </inertial>
  </link>

   <joint name="rear_left_swivel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="left_bar"/>
    <child link="rear_left_swivel"/>
    <origin rpy="0 0 0" xyz="${chair_length/2} 0.0 -${chair_height/8}"/>
    <dynamics damping="0.0" friction="0.5" />
  </joint>

  <joint name="rear_left_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="rear_left_swivel"/>
    <child link="rear_left_wheel"/>
    <origin rpy="1.57075 0 0" xyz="0.065 0 0"/>
    <dynamics damping="0" friction="0.5" />
  </joint>

  <link name="rear_left_wheel">
    <visual>
      <geometry>
        <cylinder length="0.05" radius="${small_wheel_radius}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="${small_wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <mass value="${small_wheel_weight}"/>
      <xacro:cylinder_intertia length="${small_wheel_length}" radius="${small_wheel_radius}" weight="${small_wheel_weight}" />
    </inertial>
  </link>    

  <!-- Transmission is important to link the joints and the controller -->
  <transmission name="right_main_wheel_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_main_wheel_joint" >
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_main_wheel_joint_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="left_main_wheel_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_main_wheel_joint">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_main_wheel_joint_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
</robot>
