<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wheelchair">
<xacro:include filename="$(find baxter_wheelchair_description)/urdf/wheelchair_description.xacro" />

<gazebo>
  <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
    <robotNamespace>/</robotNamespace>
    <alwaysOn>true</alwaysOn>
    <updateRate>50</updateRate>
    <leftJoint>left_main_wheel_joint</leftJoint>
    <rightJoint>right_main_wheel_joint</rightJoint>
    <wheelSeparation>${chair_width}</wheelSeparation>
    <wheelDiameter>${main_wheel_radius*2}</wheelDiameter>
    <torque>20</torque>
    <commandTopic>cmd_vel</commandTopic>
    <odometryTopic>odom</odometryTopic>
    <odometryFrame>odom</odometryFrame>
    <robotBaseFrame>base_footprint</robotBaseFrame>
  </plugin>
</gazebo>

<gazebo>
  <plugin name="imu_controller" filename="libhector_gazebo_ros_imu.so">
    <robotNamespace>/</robotNamespace>
    <updateRate>50.0</updateRate>
    <bodyName>imu_link</bodyName>
    <frameId>imu_link</frameId>
    <topicName>imu/data</topicName>
    <rpyOffsets>0 0 0</rpyOffsets> <!-- deprecated -->
    <gaussianNoise>0</gaussianNoise>  <!-- deprecated -->
    <accelDrift>0.5 0.5 0.5</accelDrift>
    <accelGaussianNoise>0.05 0.05 0.05</accelGaussianNoise>
    <rateDrift>0.1 0.1 0.1</rateDrift>
    <rateGaussianNoise>0.05 0.05 0.015</rateGaussianNoise>
    <headingDrift>0.1</headingDrift>
    <headingGaussianNoise>0.05</headingGaussianNoise>
  </plugin>
</gazebo>  

<gazebo>
  <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
    <robotNamespace>/</robotNamespace>
  </plugin>
</gazebo>

<gazebo>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <robotNamespace>/robot/</robotNamespace>
      <jointName>front_right_swivel_joint, front_right_wheel_joint, front_left_swivel_joint, front_left_wheel_joint, rear_right_swivel_joint, rear_right_wheel_joint, rear_left_swivel_joint, rear_left_wheel_joint</jointName>
      <updateRate>50.0</updateRate>
      <alwaysOn>true</alwaysOn>
    </plugin>
</gazebo>

<gazebo>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <robotNamespace>/</robotNamespace>
      <jointName>front_right_swivel_joint, front_right_wheel_joint, front_left_swivel_joint, front_left_wheel_joint, rear_right_swivel_joint, rear_right_wheel_joint, rear_left_swivel_joint, rear_left_wheel_joint</jointName>
      <updateRate>50.0</updateRate>
      <alwaysOn>true</alwaysOn>
    </plugin>
</gazebo>

<!-- Gazebo Material Colors -->

<gazebo reference="base_link">
  <material>Gazebo/DarkGrey</material>
</gazebo>

<gazebo reference="right_bar">
  <material>Gazebo/Blue</material>
</gazebo>

<gazebo reference="left_bar">
  <material>Gazebo/Blue</material>
</gazebo>

<gazebo reference="right_main_wheel">
  <material>Gazebo/Black</material>
</gazebo>

<gazebo reference="left_main_wheel">
  <material>Gazebo/Black</material>
</gazebo>

<gazebo reference="front_right_swivel">
  <material>Gazebo/DarkGrey</material>
</gazebo>

<gazebo reference="front_right_wheel">
  <material>Gazebo/Black</material>
</gazebo>

<gazebo reference="front_left_swivel">
  <material>Gazebo/DarkGrey</material>
</gazebo>

<gazebo reference="front_left_wheel">
  <material>Gazebo/Black</material>
</gazebo>

<gazebo reference="rear_right_swivel">
  <material>Gazebo/DarkGrey</material>
</gazebo>

<gazebo reference="rear_right_wheel">
  <material>Gazebo/Black</material>
</gazebo>

<gazebo reference="rear_left_swivel">
  <material>Gazebo/DarkGrey</material>
</gazebo>

<gazebo reference="rear_left_wheel">
  <material>Gazebo/Black</material>
</gazebo>

</robot>
